language: python
python:
    - "3.4"
before_install:
    - make init
    - pip install pytest pytest-xdist pytest-cov coveralls
script:
    - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
    - make test
    - kill %1
after_success:
    - coveralls
